version: '3'

services:
  moodle:
    build: ./moodle
    volumes:
      - ./siteroot:/siteroot
    environment:
      TZ: "Australia/Melbourne"
    networks:
      static:
        ipv4_address: 172.99.0.2
  moodle-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: moodle
      POSTGRES_USER: moodle_user
    volumes: 
      - 'moodledb:/var/lib/postgresql'
    environment:
      TZ: "Australia/Melbourne"
    networks:
      static:
        ipv4_address: 172.99.0.3
volumes:
    moodledb:
networks:
  static:
    driver: bridge
    ipam:
      config:
        - subnet: 172.99.0.0/16
